### ISSUE TITLE
use_color_mode panic with 0.13.5

### ISSUE THREAD

**Issue by nlfiedler** [Synphonyte/leptos-use#179]
I'm including `leptos-use` like so in the `Cargo.toml` file:

```toml
leptos-use = "0.13.5"
```

The code that presumably results in the panic:

```rust
let UseColorModeReturn { mode, set_mode, .. } = use_color_mode();
```

The error in the console is pretty brief:

```
thread 'main' panicked at /Users/nfiedler/.cargo/registry/src/index.crates.io-6f17d22bba15001f/js-sys-0.3.70/src/lib.rs:6035:9:
cannot call wasm-bindgen imported functions on non-wasm targets
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/thread/local.rs:260:26:
cannot access a Thread Local Storage value during or after destruction: AccessError
fatal runtime error: thread local panicked on drop
```

Any suggestions for how I can fix whatever I'm doing wrong? On a related note, I'm using `use_drop_zone_with_options()` with success on another page, but if I reload that page in the browser, a panic with a long stack trace appears in the console. Perhaps I'm doing something fundamentally wrong. The code for the drop zone usage, if you want to see it, is here: https://github.com/nlfiedler/tanuki/blob/main/src/preso/leptos/client/upload.rs

Versions: Rust 1.82, leptos 0.6.15, wasm-bindgen 0.2.93

Thank you.

**Comment by nlfiedler** [comment]
Just tried using `use_local_storage()` and that, too, results in an immediate panic with the same `cannot call wasm-bindgen imported functions on non-wasm targets` error. How am I doing this so wrong?

**Comment by maccesch** [comment]
Looks like you're using SSR without having configured it correctly. https://leptos-use.rs/server_side_rendering.html
